#!/usr/bin/env python

"""Combine multiple cma records (with same length) into a single one

Usage: cma-combine
"""

from biocma import cma

def combine(cma_file):
    p = cma.parse(cma_file)
    rec = p.next()
    idx = rec['sequences'][-1]['index']
    for i in p:
        seqs = i['sequences']
        for j in seqs:
            j['index'] += idx
        rec['sequences'].extend(seqs)
        idx += i['sequences'][-1]['index']
    cma.write(rec, 'combined.cma')

if __name__ == '__main__':
    import sys
    combine(sys.argv[1])
